global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
#    metrics_path: '/prometheus-metrics/metrics'
    static_configs:
      - targets:
        - localhost:8000
#      ['host.docker.internal:8000']
#      - targets: ['127.0.0.1:8000']